laravel/routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\StoreController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [StoreController::class, 'index'])->name('store');
Route::post('/addtocart', [StoreController::class, 'addtocart'])->name('addcart');
Route::get('/cart', [StoreController::class, 'cart'])->name('cart');
Route::post('/updatecart', [StoreController::class, 'updatecart'])->name('updatecart');
Route::post('/deleteitem', [StoreController::class, 'deleteitem'])->name('deleteitem');

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware(['auth'])->name('dashboard');
Route::get('/products', [ProductsController::class, 'index'])->middleware(['auth'])->name('products');
Route::get('/products/add', [ProductsController::class, 'create'])->middleware(['auth'])->name('products.add');
Route::post('/products/store', [ProductsController::class, 'store'])->middleware(['auth'])->name('products.store');
Route::get('/product/edit/{id}', [ProductsController::class, 'edit'])->middleware('auth')->name('products.edit');
Route::post('/products/update', [ProductsController::class, 'update'])->middleware(['auth'])->name('products.update');
Route::post('/products/delete', [ProductsController::class, 'destroy'])->middleware(['auth'])->name('products.destroy');

require __DIR__.'/auth.php';

laravel/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

laravel/app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

laravel/resources/views/addProducts.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Add new product') }}
        </h2>
    </x-slot>
    <div class="max-w-screen-sm mx-auto mt-16">
        <form action="{{route('products.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <x-label for="name" :value="__('Name')" />
            <x-input id="name" class="block mt-1 w-full" type="text" name="name" :value="old('name')" autofocus />
            @error('name')
            <p class="text-xs text-red-400">{{$message}}</p>
            @enderror

            <x-label for="description" :value="__('Description')" />
            <x-input id="description" class="block mt-1 w-full" type="text" name="description" :value="old('description')" autofocus />
            @error('description')
            <p class="text-xs text-red-400">{{$message}}</p>
            @enderror

            <x-label for="price" :value="__('Price')" />
            <x-input id="price" class="block mt-1 w-full" type="text" name="price" :value="old('price')" autofocus />
            @error('price')
            <p class="text-xs text-red-400">{{$message}}</p>
            @enderror

            <x-label for="image">Add image</x-label>
            <input name="image" id="image" class="mt-1" type="file">

            <button class="px-2 py-1" type="submit">Submit</button>
        </form>
    </div>
</x-app-layout>

laravel/resources/views/cart.blade.php
<x-guest-layout>
    <h1 class="w-12 mx-auto text-2xl mt-8">Ostukorv</h1>
    @if (empty($cart))
        <p>The cart is empty</p>
    @else
    <div class="p-3">
        <div class="overflow-x-auto">
            <table class="table-auto w-screen-lg mx-auto">
                <thead class="text-xs font-semibold uppercase text-gray-400 bg-gray-50">
                    <tr>
                        <th class="p-2 whitespace-nowrap">
                            <div class="font-semibold text-left">Product</div>
                        </th>
                        <th class="p-2 whitespace-nowrap">
                            <div class="font-semibold text-left">Description</div>
                        </th>
                        <th class="p-2 whitespace-nowrap">
                            <div class="font-semibold text-left">Price</div>
                        </th>
                        <th class="p-2 whitespace-nowrap">
                            <div class="font-semibold text-center">Total</div>
                        </th>
                        <th class="p-2 whitespace-nowrap">

                        </th>
                        <th class="p-2 whitespace-nowrap">

                        </th>
                    </tr>
                </thead>
                <tbody class="text-sm divide-y divide-gray-100">
                    @foreach ($cart as $product)
                    <tr>
                        <td class="p-2 whitespace-nowrap">
                            <div class="flex items-center">
                                <div class="w-10 h-10 flex-shrink-0 mr-2 sm:mr-3"><img src="{{$product['image']}}" class="w-12 h-12 border-md"></div>
                                <div class="font-medium text-gray-800">{{$product['name']}}</div>
                            </div>
                        </td>
                        <td class="p-2">
                            <div class="text-left">{{$product['description']}}</div>
                        </td>
                        <td class="p-2 whitespace-nowrap">
                            <div class="text-left font-medium text-green-500">{{$product['price']}}€</div>
                        </td>

                        <td class="p-2 whitespace-nowrap">
                            <div class="text-left font-medium text-green-500">{{$product['price']*$product['quantity']}}€</div>
                        </td>
                        <td class="p-2 whitespace-nowrap">
                            <div class="text-lg text-center">
                                <form action="{{route('updatecart')}}" method="post">
                                    @csrf
                                    <input type="hidden" name="id" value="{{$product['id']}}">
                                    <input type="number" value="{{$product['quantity']}}" name="quantity" class="w-16 h-8">
                                    <button type="submit" class="bg-blue-500 rounded-full text-white px-4 mx-8">Update cart</button>
                                </form>
                            </div>
                        </td>
                        <td class="p-2 whitespace-nowrap">
                            <form action="{{route('deleteitem')}}" method="post">
                                @csrf
                                <input type="hidden" name="id" value="{{$product['id']}}">
                                <button type="submit" class="bg-red-500 rounded-full text-white px-4 bg-opacity-80">Delete item</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    @endif
</x-guest-layout>

laravel/resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                    @foreach ($users as $user)
                        <p>{{$user->name}}</p>
                        <p>{{$user->email}}</p>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

laravel/resources/views/editProducts.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit product') }}
        </h2>
    </x-slot>
    <div class="max-w-screen-sm mx-auto mt-16">
        <form action="{{route('products.update')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <input type="hidden" name="id" id="id" value="{{$product->id}}">
            <x-label for="name" :value="__('Name')" />
            <x-input id="name" class="block mt-1 w-full" type="text" name="name" :value="$product->name ?? old('name')" autofocus />
            @error('name')
            <p class="text-xs text-red-400">{{$message}}</p>
            @enderror

            <x-label for="description" :value="__('Description')" />
            <x-input id="description" class="block mt-1 w-full" type="text" name="description" :value="$product->description ?? old('description')" autofocus />
            @error('description')
            <p class="text-xs text-red-400">{{$message}}</p>
            @enderror

            <x-label for="price" :value="__('Price')" />
            <x-input id="price" class="block mt-1 w-full" type="text" name="price" :value="$product->price ?? old('price')" autofocus />
            @error('price')
            <p class="text-xs text-red-400">{{$message}}</p>
            @enderror

            <x-label for="image">Add image</x-label>
            <input name="image" id="image" class="mt-1" type="file">

            <button class="px-2 py-1" type="submit">Submit</button>
        </form>
    </div>
</x-app-layout>

laravel/resources/views/products.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Products') }}
        </h2>
    </x-slot>

    <div class="flex flex-col w-7/12 mx-auto">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                  <tr>
                    <th scope="col" class="px-12 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                         Name
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Description
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                         Price
                    </th>
                    <th scope="col" class="relative px-6 py-3">
                        <span class="sr-only">Edit</span>
                    </th>
                    <th scope="col" class="px-6 py-3 text-right text-xs font-medium uppercase tracking-wider">
                        <a class="bg-gray-300 rounded" href="{{route('products.add')}}">Add new product</a>
                    </th>
                  </tr>
                </thead>
                @foreach ($products as $product)
                <tbody class="bg-white divide-y divide-gray-200">
                  <tr class="odd:bg-gray-500 even:bg-white"">
                    <td class="px-6 py-4 whitespace-nowrap">
                      <div class="flex items-center">
                        <div class="flex-shrink-0 h-16 w-16">
                          <img class="h-16 w-16 rounded-full" src="{{$product->image}}" alt="">
                        </div>
                        <div class="ml-4">
                          <div class="text-sm font-medium text-gray-900">
                            {{$product->name}}
                          </div>
                        </div>
                      </div>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <div class="text-sm text-gray-900">{{$product->description}}</div>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                        {{$product->price}} €
                      </span>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <a href="{{route('products.edit', $product->id)}}" class="text-indigo-600 hover:text-indigo-900">Edit</a>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <form action="{{route('products.destroy')}}" method="post">
                            @csrf
                            <input type="hidden" name="id" value="{{$product->id}}">
                            <button type="submit" class="text-red-600">Delete</button>
                        </form>
                      </td>
                  </tr>
                  @endforeach
                  <!-- More people... -->
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
</x-app-layout>